//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Itspecialist.Managers
{
    [Codelisk.GeneratorAttributes.GeneratorAttributes.GeneratedManagerAttribute]
    [Codelisk.GeneratorAttributes.GeneralAttributes.Registration.RegisterTransient]
    public partial class CareerOpportunityManager22 : DefaultUserManager<CareerOpportunityDto, Guid, CareerOpportunityEntity>, ICareerOpportunityManager
    {
        readonly IDistrictRepository _districtRepository;
        readonly ISkillsRepository _skillsRepository;

        public CareerOpportunityManager22(IDistrictRepository districtRepository, ISkillsRepository skillsRepository, ICareerOpportunityRepository careerOpportunityRepository, IMapper iMapper)
            : base(careerOpportunityRepository, iMapper)
        {
            _districtRepository = districtRepository;
            _skillsRepository = skillsRepository;
        }

        [GetFullAttribute]
        public override async Task<List<CareerOpportunityFull>> GetAllFull()
        {
            List<CareerOpportunityFull> careerOpportunityFulls = new();
            var careerOpportunityDtos = await GetAll();
            foreach (var careerOpportunityDto in careerOpportunityDtos)
            {
               // careerOpportunityFulls.Add(await GetFull(careerOpportunityDto.GetId()));
            }
            return careerOpportunityFulls;
        }

        [GetFullAttribute]
        public override async Task<CareerOpportunityFull> GetFull<CareerOpportunityFull>(Guid id)
        {
            CareerOpportunityFull CareerOpportunityFull = new();
            var careerOpportunityDto = await Get(id);
            CareerOpportunityFull.district = await _districtRepository.Get(careerOpportunityDto.GetId());
            CareerOpportunityFull.skills = await _skillsRepository.Get(careerOpportunityDto.GetId());
            return CareerOpportunityFull;
        }
    }
}
