//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Itspecialist.Repositories
{
    [Codelisk.GeneratorAttributes.GeneratorAttributes.GeneratedRepositoryAttribute]
    [Codelisk.GeneratorAttributes.GeneralAttributes.Registration.RegisterTransient]
    public partial class FavoriteOpportunityRepository2 : DefaultUserRepository<FavoriteOpportunityEntity, Guid>, IFavoriteOpportunityRepository
    {
        public FavoriteOpportunityRepository2(DefaultRepositoryProvider defaultRepositoryProvider)
            : base(defaultRepositoryProvider)
        {
        }
    }
}
